// Liste de villes utilisée par défaut pour les audits (≈190 communes françaises).
// L'utilisateur peut la remplacer dans l'interface. Doublons retirés.

export const TOP_CITIES = [
  "Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Montpellier",
  "Strasbourg", "Bordeaux", "Lille", "Rennes", "Reims", "Saint-Étienne",
  "Toulon", "Le Havre", "Grenoble", "Dijon", "Angers", "Nîmes", "Villeurbanne",
  "Clermont-Ferrand", "Saint-Denis", "Aix-en-Provence", "Brest", "Limoges",
  "Tours", "Amiens", "Metz", "Perpignan", "Boulogne-Billancourt", "Besançon",
  "Orléans", "Rouen", "Mulhouse", "Caen", "Saint-Denis de La Réunion", "Nancy",
  "Argenteuil", "Montreuil", "Saint-Paul de La Réunion", "Roubaix", "Tourcoing",
  "Nanterre", "Avignon", "Créteil", "Poitiers", "Courbevoie", "Versailles",
  "Pau", "Vitry-sur-Seine", "Colombes", "Aulnay-sous-Bois", "La Rochelle",
  "Antibes", "Saint-Pierre de La Réunion", "Champigny-sur-Marne",
  "Rueil-Malmaison", "Béziers", "Saint-Maur-des-Fossés", "Drancy",
  "Aubervilliers", "Calais", "Dunkerque", "Colmar", "Mérignac",
  "Asnières-sur-Seine", "Levallois-Perret", "Issy-les-Moulineaux", "Quimper",
  "Noisy-le-Grand", "La Seyne-sur-Mer", "Villeneuve-d'Ascq", "Neuilly-sur-Seine",
  "Cergy", "Troyes", "Niort", "Ajaccio", "Bourges", "Clichy", "Lorient",
  "Pessac", "Ivry-sur-Seine", "Tulle", "Chambéry", "Angoulême", "Annecy",
  "Valence", "Cholet", "Sartrouville", "Le Mans", "Saint-Quentin",
  "Châlons-en-Champagne", "Vannes", "Albi", "Sète", "Évry-Courcouronnes",
  "Chartres", "Meaux", "Pantin", "Blois", "Épinay-sur-Seine", "Arles",
  "La Roche-sur-Yon", "Maisons-Alfort", "Sevran", "Chalon-sur-Saône", "Cannes",
  "Bagneux", "Wattrelos", "Montauban", "Villejuif", "Saint-Nazaire",
  "Saint-Malo", "Castres", "Choisy-le-Roi", "Saint-Brieuc", "Bayonne",
  "Charleville-Mézières", "Melun", "Gap", "Rosny-sous-Bois", "Laval",
  "Saint-Herblain", "Vitrolles", "Saint-Martin-d'Hères", "Alfortville",
  "Thionville", "Salon-de-Provence", "Saint-Priest", "Caluire-et-Cuire",
  "Nevers", "Montrouge", "Beauvais", "Agen", "Lormont", "Garges-lès-Gonesse",
  "Châteauroux", "Six-Fours-les-Plages", "Carcassonne", "Armentières",
  "Pontault-Combault", "Savigny-sur-Orge", "Conflans-Sainte-Honorine",
  "Châtillon", "Mantes-la-Jolie", "Orange", "Bondy", "La Courneuve",
  "Villenave-d'Ornon", "Montélimar", "Pontoise", "Sainte-Geneviève-des-Bois",
  "Massy", "Saint-Martin-Boulogne", "Istres", "Douai", "Chilly-Mazarin",
  "Saint-Ouen-sur-Seine", "Le Cannet", "Houilles", "Montargis",
  "Villefranche-sur-Saône", "Saint-Omer", "La Garenne-Colombes", "Saint-Joseph",
  "Fontenay-sous-Bois", "Haguenau", "Thiers", "Vienne", "Gagny", "Antony",
  "Abbeville", "Lambersart", "Châtellerault", "Fresnes", "Thonon-les-Bains",
  "Montmorency", "Chalonnes-sur-Loire", "Valenton", "Marignane", "Cagnes-sur-Mer",
  "Saint-Médard-en-Jalles", "Villeneuve-Saint-Georges", "Les Lilas", "Élancourt",
  "Plaisir", "Maubeuge", "Tarbes", "Torcy", "Ris-Orangis", "Sin-le-Noble",
  "Toul", "Langres", "Rambouillet", "Creil", "L'Haÿ-les-Roses", "Grasse",
  "Saint-Amand-les-Eaux",
];
